site_name: Puente Chill
docs/
  clau.jpeg
  fuego.jpeg
  notion1.png
  notion2.png
  notion3.png
  veraHelena.png
nav:
  - Inicio: index.md
  - Subpáginas:
    - Subpágina 1: php.md
    - Subpágina 2: social.md
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - php
    - javascript
extra_css:
  -'style.css'

