site_name: Puente Chill

theme: material

markdown_extensions:
  - pymdownx.superfences

nav:
  - 'Inicio': 'index.md'
  - 'Subpáginas':
    - 'Subpágina 1': 'php.md'
    - 'Subpágina 2': 'social.md'
  - highlightjs: true
    hljs_languages:
      - yaml
      - php
      - javascript
  - extra_css:
    -'style.css'

log:
  level: debug
  handlers:
    - console
    - file
  - <log end>


