DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    EMAIL VARCHAR(30) PRIMARY KEY UNIQUE,
    PASSWORD VARCHAR(80),
    NAME VARCHAR(20),
    LINK VARCHAR(30)
);

DROP TABLE IF EXISTS TOKENS;

CREATE TABLE TOKENS (
    ID INT(11) UNSIGNED AUTO_INCREMENT NOT NULL,
    TOKEN CHAR(60),
    USERID VARCHAR(30) NOT NULL,
    EXPIRES INT(11), -- METEREMOS EL VALOR EN SEGS
    TIPO ENUM('ACTIVATE', 'REMEMBER', 'RECOVERY') NOT NULL, -- Nuevo campo 'TYPE'
    PRIMARY KEY (ID)
);
